{
  "uid" : "2a74b0c2b63df82a",
  "name" : "test_setlogin_always",
  "fullName" : "testEntrustSetup.test_Qentrust_setup.TestEntrustSetup#test_setlogin_always",
  "historyId" : "0eb23ef7699fb84b2144a3f6425e5b8a",
  "time" : {
    "start" : 1652795185926,
    "stop" : 1652795189412,
    "duration" : 3486
  },
  "status" : "broken",
  "statusMessage" : "AttributeError: module 'pytest' has no attribute 'assume'",
  "statusTrace" : "self = <testcases.testEntrustSetup.test_Qentrust_setup.TestEntrustSetup object at 0x00D8DC90>\nsetup_fixture = (<businessPage.trade_first_page.TradeFirst object at 0x00D8DBB0>, <businessPage.entrust_setup_page.Setup object at 0x0...<businessPage.choice_oder_page.ChoiceOrder object at 0x00D8D0B0>, <businessPage.order_page.Order object at 0x00D8D490>)\n\n    @pytest.mark.usefixtures('back_fixture')\n    def test_setlogin_always(self,setup_fixture):\n        tradehome, setup,choiceorder,order = setup_fixture\n        setup.setlogin_always()\n        setlogin_text = setup.el_text(setup.rl_setting_login_time,\"设置登录时长text\")\n>       pytest.assume(setlogin_text == \"始终登录\")\nE       AttributeError: module 'pytest' has no attribute 'assume'\n\ntestEntrustSetup\\test_Qentrust_setup.py:198: AttributeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "driver_fixture",
    "time" : {
      "start" : 1652794360868,
      "stop" : 1652794396581,
      "duration" : 35713
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "back_fixture",
    "time" : {
      "start" : 1652795182549,
      "stop" : 1652795182549,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "login_fixture",
    "time" : {
      "start" : 1652794396581,
      "stop" : 1652794501486,
      "duration" : 104905
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "setup_fixture",
    "time" : {
      "start" : 1652795182549,
      "stop" : 1652795185926,
      "duration" : 3377
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "AttributeError: module 'pytest' has no attribute 'assume'",
    "statusTrace" : "self = <testcases.testEntrustSetup.test_Qentrust_setup.TestEntrustSetup object at 0x00D8DC90>\nsetup_fixture = (<businessPage.trade_first_page.TradeFirst object at 0x00D8DBB0>, <businessPage.entrust_setup_page.Setup object at 0x0...<businessPage.choice_oder_page.ChoiceOrder object at 0x00D8D0B0>, <businessPage.order_page.Order object at 0x00D8D490>)\n\n    @pytest.mark.usefixtures('back_fixture')\n    def test_setlogin_always(self,setup_fixture):\n        tradehome, setup,choiceorder,order = setup_fixture\n        setup.setlogin_always()\n        setlogin_text = setup.el_text(setup.rl_setting_login_time,\"设置登录时长text\")\n>       pytest.assume(setlogin_text == \"始终登录\")\nE       AttributeError: module 'pytest' has no attribute 'assume'\n\ntestEntrustSetup\\test_Qentrust_setup.py:198: AttributeError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "3fc1c4773ff9385",
      "name" : "log",
      "source" : "3fc1c4773ff9385.txt",
      "type" : "text/plain",
      "size" : 526
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 1
  },
  "afterStages" : [ {
    "name" : "driver_fixture::0",
    "time" : {
      "start" : 1652796124797,
      "stop" : 1652796124797,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "back_fixture::0",
    "time" : {
      "start" : 1652795189421,
      "stop" : 1652795189550,
      "duration" : 129
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('back_fixture')"
  }, {
    "name" : "parentSuite",
    "value" : "testEntrustSetup"
  }, {
    "name" : "suite",
    "value" : "test_Qentrust_setup"
  }, {
    "name" : "subSuite",
    "value" : "TestEntrustSetup"
  }, {
    "name" : "host",
    "value" : "Win102021AVUCSJ"
  }, {
    "name" : "thread",
    "value" : "10404-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testEntrustSetup.test_Qentrust_setup"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "204dff7d27a29f7a",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details",
      "time" : {
        "start" : 1652713051397,
        "stop" : 1652713051397,
        "duration" : 0
      }
    }, {
      "uid" : "bc8cc92c48f5bf7c",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details",
      "time" : {
        "start" : 1652712707802,
        "stop" : 1652712707802,
        "duration" : 0
      }
    }, {
      "uid" : "e358536d8f642d5a",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652710822630,
        "stop" : 1652710822630,
        "duration" : 0
      }
    }, {
      "uid" : "55b5f90b8227f76e",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652710342521,
        "stop" : 1652710342521,
        "duration" : 0
      }
    }, {
      "uid" : "c14084347052b6dd",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20093ms.",
      "time" : {
        "start" : 1652710086866,
        "stop" : 1652710086866,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "@pytest.mark.usefixtures('back_fixture')" ]
  },
  "source" : "2a74b0c2b63df82a.json",
  "parameterValues" : [ ]
}