{
  "uid" : "64a375d6ff54f418",
  "name" : "test_rise",
  "fullName" : "testContractScreen.test_Qcontract_screen.TestContractScreen#test_rise",
  "historyId" : "5a857fb485dd391f77bd3805ea5e0699",
  "time" : {
    "start" : 1652794950979,
    "stop" : 1652794955727,
    "duration" : 4748
  },
  "status" : "broken",
  "statusMessage" : "AttributeError: module 'pytest' has no attribute 'assume'",
  "statusTrace" : "self = <testcases.testContractScreen.test_Qcontract_screen.TestContractScreen object at 0x005F6B50>\nsetup_fixture = (<businessPage.contract_screen_page.Screen object at 0x005F6070>, <businessPage.first_page.First object at 0x005F6830>, <businessPage.optional_page.Optional object at 0x005F6610>)\n\n    @pytest.mark.usefixtures('back_fixture')\n    def test_rise(self, setup_fixture):\n        screen,first,optional = setup_fixture\n        # 降序\n        screen.c_rise()\n        res = screen.desc(2)\n>       pytest.assume(res == True)\nE       AttributeError: module 'pytest' has no attribute 'assume'\n\ntestContractScreen\\test_Qcontract_screen.py:42: AttributeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "driver_fixture",
    "time" : {
      "start" : 1652794360868,
      "stop" : 1652794396581,
      "duration" : 35713
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "login_fixture",
    "time" : {
      "start" : 1652794396581,
      "stop" : 1652794501486,
      "duration" : 104905
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "setup_fixture",
    "time" : {
      "start" : 1652794947755,
      "stop" : 1652794950979,
      "duration" : 3224
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "back_fixture",
    "time" : {
      "start" : 1652794947755,
      "stop" : 1652794947755,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "AttributeError: module 'pytest' has no attribute 'assume'",
    "statusTrace" : "self = <testcases.testContractScreen.test_Qcontract_screen.TestContractScreen object at 0x005F6B50>\nsetup_fixture = (<businessPage.contract_screen_page.Screen object at 0x005F6070>, <businessPage.first_page.First object at 0x005F6830>, <businessPage.optional_page.Optional object at 0x005F6610>)\n\n    @pytest.mark.usefixtures('back_fixture')\n    def test_rise(self, setup_fixture):\n        screen,first,optional = setup_fixture\n        # 降序\n        screen.c_rise()\n        res = screen.desc(2)\n>       pytest.assume(res == True)\nE       AttributeError: module 'pytest' has no attribute 'assume'\n\ntestContractScreen\\test_Qcontract_screen.py:42: AttributeError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "66ece832aabac820",
      "name" : "log",
      "source" : "66ece832aabac820.txt",
      "type" : "text/plain",
      "size" : 622
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 1
  },
  "afterStages" : [ {
    "name" : "driver_fixture::0",
    "time" : {
      "start" : 1652796124797,
      "stop" : 1652796124797,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "back_fixture::0",
    "time" : {
      "start" : 1652794955733,
      "stop" : 1652794955876,
      "duration" : 143
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('back_fixture')"
  }, {
    "name" : "parentSuite",
    "value" : "testContractScreen"
  }, {
    "name" : "suite",
    "value" : "test_Qcontract_screen"
  }, {
    "name" : "subSuite",
    "value" : "TestContractScreen"
  }, {
    "name" : "host",
    "value" : "Win102021AVUCSJ"
  }, {
    "name" : "thread",
    "value" : "10404-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testContractScreen.test_Qcontract_screen"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "429bd8554f2020f2",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0400E0D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1652793915513,
        "stop" : 1652793915513,
        "duration" : 0
      }
    }, {
      "uid" : "6ac48fc8c7eb6bb",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details",
      "time" : {
        "start" : 1652713045342,
        "stop" : 1652713045342,
        "duration" : 0
      }
    }, {
      "uid" : "41ed20d5a821eec6",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details",
      "time" : {
        "start" : 1652712701795,
        "stop" : 1652712701795,
        "duration" : 0
      }
    }, {
      "uid" : "48b2a8932e87e7fe",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652710821982,
        "stop" : 1652710821982,
        "duration" : 0
      }
    }, {
      "uid" : "26b5f2da96a23152",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652710341875,
        "stop" : 1652710341875,
        "duration" : 0
      }
    }, {
      "uid" : "7d30aac951ea00ad",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20093ms.",
      "time" : {
        "start" : 1652710085848,
        "stop" : 1652710085848,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "@pytest.mark.usefixtures('back_fixture')" ]
  },
  "source" : "64a375d6ff54f418.json",
  "parameterValues" : [ ]
}