{
  "uid" : "7a30cbffeb4fcf48",
  "name" : "test_setlogin_30",
  "fullName" : "testEntrustSetup.test_Qentrust_setup.TestEntrustSetup#test_setlogin_30",
  "historyId" : "da2e04d6233bc5567f7389b2c38d0458",
  "time" : {
    "start" : 1652795178748,
    "stop" : 1652795182391,
    "duration" : 3643
  },
  "status" : "broken",
  "statusMessage" : "AttributeError: module 'pytest' has no attribute 'assume'",
  "statusTrace" : "self = <testcases.testEntrustSetup.test_Qentrust_setup.TestEntrustSetup object at 0x006032D0>\nsetup_fixture = (<businessPage.trade_first_page.TradeFirst object at 0x006032B0>, <businessPage.entrust_setup_page.Setup object at 0x0...<businessPage.choice_oder_page.ChoiceOrder object at 0x006038B0>, <businessPage.order_page.Order object at 0x006039F0>)\n\n    @pytest.mark.usefixtures('back_fixture')\n    def test_setlogin_30(self,setup_fixture):\n        tradehome, setup,choiceorder,order = setup_fixture\n        setup.setlogin_30()\n        setlogin_text = setup.el_text(setup.rl_setting_login_time,\"设置登录时长text\")\n>       pytest.assume(setlogin_text == \"30分钟后自动退出\")\nE       AttributeError: module 'pytest' has no attribute 'assume'\n\ntestEntrustSetup\\test_Qentrust_setup.py:192: AttributeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "back_fixture",
    "time" : {
      "start" : 1652795175682,
      "stop" : 1652795175682,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "driver_fixture",
    "time" : {
      "start" : 1652794360868,
      "stop" : 1652794396581,
      "duration" : 35713
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "login_fixture",
    "time" : {
      "start" : 1652794396581,
      "stop" : 1652794501486,
      "duration" : 104905
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "setup_fixture",
    "time" : {
      "start" : 1652795175682,
      "stop" : 1652795178748,
      "duration" : 3066
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "AttributeError: module 'pytest' has no attribute 'assume'",
    "statusTrace" : "self = <testcases.testEntrustSetup.test_Qentrust_setup.TestEntrustSetup object at 0x006032D0>\nsetup_fixture = (<businessPage.trade_first_page.TradeFirst object at 0x006032B0>, <businessPage.entrust_setup_page.Setup object at 0x0...<businessPage.choice_oder_page.ChoiceOrder object at 0x006038B0>, <businessPage.order_page.Order object at 0x006039F0>)\n\n    @pytest.mark.usefixtures('back_fixture')\n    def test_setlogin_30(self,setup_fixture):\n        tradehome, setup,choiceorder,order = setup_fixture\n        setup.setlogin_30()\n        setlogin_text = setup.el_text(setup.rl_setting_login_time,\"设置登录时长text\")\n>       pytest.assume(setlogin_text == \"30分钟后自动退出\")\nE       AttributeError: module 'pytest' has no attribute 'assume'\n\ntestEntrustSetup\\test_Qentrust_setup.py:192: AttributeError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "57ec4e9ce7ecf57f",
      "name" : "log",
      "source" : "57ec4e9ce7ecf57f.txt",
      "type" : "text/plain",
      "size" : 537
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 1
  },
  "afterStages" : [ {
    "name" : "back_fixture::0",
    "time" : {
      "start" : 1652795182398,
      "stop" : 1652795182546,
      "duration" : 148
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "driver_fixture::0",
    "time" : {
      "start" : 1652796124797,
      "stop" : 1652796124797,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('back_fixture')"
  }, {
    "name" : "parentSuite",
    "value" : "testEntrustSetup"
  }, {
    "name" : "suite",
    "value" : "test_Qentrust_setup"
  }, {
    "name" : "subSuite",
    "value" : "TestEntrustSetup"
  }, {
    "name" : "host",
    "value" : "Win102021AVUCSJ"
  }, {
    "name" : "thread",
    "value" : "10404-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testEntrustSetup.test_Qentrust_setup"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "2d2533fb6e0c796c",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details",
      "time" : {
        "start" : 1652713051110,
        "stop" : 1652713051110,
        "duration" : 0
      }
    }, {
      "uid" : "17ecf85f0c393808",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details",
      "time" : {
        "start" : 1652712707522,
        "stop" : 1652712707522,
        "duration" : 0
      }
    }, {
      "uid" : "8477d8a402c89385",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652710822602,
        "stop" : 1652710822602,
        "duration" : 0
      }
    }, {
      "uid" : "c534d4ea9d5066b9",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652710342492,
        "stop" : 1652710342492,
        "duration" : 0
      }
    }, {
      "uid" : "bb1c4f807325c84c",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20093ms.",
      "time" : {
        "start" : 1652710086821,
        "stop" : 1652710086821,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "@pytest.mark.usefixtures('back_fixture')" ]
  },
  "source" : "7a30cbffeb4fcf48.json",
  "parameterValues" : [ ]
}