{
  "uid" : "7d3c326603938ec4",
  "name" : "test_setrl_sj_defaultDivideNum",
  "fullName" : "testEntrustSetup.test_Qentrust_setup.TestEntrustSetup#test_setrl_sj_defaultDivideNum",
  "historyId" : "771aa8e0477fb0304aec861d0bd4292f",
  "time" : {
    "start" : 1652795148510,
    "stop" : 1652795153407,
    "duration" : 4897
  },
  "status" : "broken",
  "statusMessage" : "AttributeError: module 'pytest' has no attribute 'assume'",
  "statusTrace" : "self = <testcases.testEntrustSetup.test_Qentrust_setup.TestEntrustSetup object at 0x00D7FAF0>\nsetup_fixture = (<businessPage.trade_first_page.TradeFirst object at 0x00D7F8B0>, <businessPage.entrust_setup_page.Setup object at 0x0...<businessPage.choice_oder_page.ChoiceOrder object at 0x00D7F4B0>, <businessPage.order_page.Order object at 0x00D7F190>)\n\n    @pytest.mark.usefixtures('back_fixture')\n    def test_setrl_sj_defaultDivideNum(self,setup_fixture):\n        tradehome, setup,choiceorder,order = setup_fixture\n        setup.setrl_sj_defaultDivideNum(5)\n        rl_sj_defaultDivideNum_text = setup.el_text(setup.rl_sj_defaultDivideNum,\"市价每单拆单张数text\")\n>       pytest.assume(rl_sj_defaultDivideNum_text == \"5\")\nE       AttributeError: module 'pytest' has no attribute 'assume'\n\ntestEntrustSetup\\test_Qentrust_setup.py:164: AttributeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "driver_fixture",
    "time" : {
      "start" : 1652794360868,
      "stop" : 1652794396581,
      "duration" : 35713
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "login_fixture",
    "time" : {
      "start" : 1652794396581,
      "stop" : 1652794501486,
      "duration" : 104905
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "setup_fixture",
    "time" : {
      "start" : 1652795145429,
      "stop" : 1652795148509,
      "duration" : 3080
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "back_fixture",
    "time" : {
      "start" : 1652795145429,
      "stop" : 1652795145429,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "AttributeError: module 'pytest' has no attribute 'assume'",
    "statusTrace" : "self = <testcases.testEntrustSetup.test_Qentrust_setup.TestEntrustSetup object at 0x00D7FAF0>\nsetup_fixture = (<businessPage.trade_first_page.TradeFirst object at 0x00D7F8B0>, <businessPage.entrust_setup_page.Setup object at 0x0...<businessPage.choice_oder_page.ChoiceOrder object at 0x00D7F4B0>, <businessPage.order_page.Order object at 0x00D7F190>)\n\n    @pytest.mark.usefixtures('back_fixture')\n    def test_setrl_sj_defaultDivideNum(self,setup_fixture):\n        tradehome, setup,choiceorder,order = setup_fixture\n        setup.setrl_sj_defaultDivideNum(5)\n        rl_sj_defaultDivideNum_text = setup.el_text(setup.rl_sj_defaultDivideNum,\"市价每单拆单张数text\")\n>       pytest.assume(rl_sj_defaultDivideNum_text == \"5\")\nE       AttributeError: module 'pytest' has no attribute 'assume'\n\ntestEntrustSetup\\test_Qentrust_setup.py:164: AttributeError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "8f181c02b6c4d798",
      "name" : "log",
      "source" : "8f181c02b6c4d798.txt",
      "type" : "text/plain",
      "size" : 732
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 1
  },
  "afterStages" : [ {
    "name" : "driver_fixture::0",
    "time" : {
      "start" : 1652796124797,
      "stop" : 1652796124797,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "back_fixture::0",
    "time" : {
      "start" : 1652795153416,
      "stop" : 1652795153525,
      "duration" : 109
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('back_fixture')"
  }, {
    "name" : "parentSuite",
    "value" : "testEntrustSetup"
  }, {
    "name" : "suite",
    "value" : "test_Qentrust_setup"
  }, {
    "name" : "subSuite",
    "value" : "TestEntrustSetup"
  }, {
    "name" : "host",
    "value" : "Win102021AVUCSJ"
  }, {
    "name" : "thread",
    "value" : "10404-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testEntrustSetup.test_Qentrust_setup"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "ff139878015f3791",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details",
      "time" : {
        "start" : 1652713050021,
        "stop" : 1652713050021,
        "duration" : 0
      }
    }, {
      "uid" : "ef3b217006df087c",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details",
      "time" : {
        "start" : 1652712706420,
        "stop" : 1652712706420,
        "duration" : 0
      }
    }, {
      "uid" : "e75a47a5b14259b0",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652710822487,
        "stop" : 1652710822487,
        "duration" : 0
      }
    }, {
      "uid" : "cad4179da6231834",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652710342380,
        "stop" : 1652710342380,
        "duration" : 0
      }
    }, {
      "uid" : "8ad33782785ee42",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20093ms.",
      "time" : {
        "start" : 1652710086627,
        "stop" : 1652710086627,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "@pytest.mark.usefixtures('back_fixture')" ]
  },
  "source" : "7d3c326603938ec4.json",
  "parameterValues" : [ ]
}