{
  "uid" : "c8a5e3e3bddfaf28",
  "name" : "test_cancel_buy",
  "fullName" : "testCancelOrder.test_Qcancelorder.TestCancelOrder#test_cancel_buy",
  "historyId" : "5b67d95dcab8662d6877883ace8bc240",
  "time" : {
    "start" : 1652794624173,
    "stop" : 1652794659594,
    "duration" : 35421
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: assert False == True\n  +False\n  -True",
  "statusTrace" : "self = <testcases.testCancelOrder.test_Qcancelorder.TestCancelOrder object at 0x00CF6FF0>\nsetup_fixture = (<businessPage.cancel_order_page.CancelOrder object at 0x00CF6BD0>, <businessPage.trade_first_page.TradeFirst object a...<businessPage.choice_oder_page.ChoiceOrder object at 0x00CF6E50>, <businessPage.order_page.Order object at 0x00CF6BF0>)\n\n    @pytest.mark.usefixtures('back_fixture')\n    def test_cancel_buy(self,setup_fixture):\n        cancleorder,tradehome,choiceorder,order= setup_fixture\n        # 构造1个买入撤单数据\n        tradehome.to_trade_page()\n        tradehome.to_order()\n        choiceorder.c_orderpage()\n        order.c_price_dtj()\n        order.c_hand(1)\n        order.c_orderbuy()\n        order.order_page_back()\n        # 进入撤单页\n        tradehome.to_cancelOrder()\n        # 撤单后买入/卖出/平仓\n        res = cancleorder.c_cancel_sell()\n>       assert res == True\nE       assert False == True\nE         +False\nE         -True\n\ntestCancelOrder\\test_Qcancelorder.py:85: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "driver_fixture",
    "time" : {
      "start" : 1652794360868,
      "stop" : 1652794396581,
      "duration" : 35713
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "login_fixture",
    "time" : {
      "start" : 1652794396581,
      "stop" : 1652794501486,
      "duration" : 104905
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "back_fixture",
    "time" : {
      "start" : 1652794624173,
      "stop" : 1652794624173,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "setup_fixture",
    "time" : {
      "start" : 1652794624173,
      "stop" : 1652794624173,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: assert False == True\n  +False\n  -True",
    "statusTrace" : "self = <testcases.testCancelOrder.test_Qcancelorder.TestCancelOrder object at 0x00CF6FF0>\nsetup_fixture = (<businessPage.cancel_order_page.CancelOrder object at 0x00CF6BD0>, <businessPage.trade_first_page.TradeFirst object a...<businessPage.choice_oder_page.ChoiceOrder object at 0x00CF6E50>, <businessPage.order_page.Order object at 0x00CF6BF0>)\n\n    @pytest.mark.usefixtures('back_fixture')\n    def test_cancel_buy(self,setup_fixture):\n        cancleorder,tradehome,choiceorder,order= setup_fixture\n        # 构造1个买入撤单数据\n        tradehome.to_trade_page()\n        tradehome.to_order()\n        choiceorder.c_orderpage()\n        order.c_price_dtj()\n        order.c_hand(1)\n        order.c_orderbuy()\n        order.order_page_back()\n        # 进入撤单页\n        tradehome.to_cancelOrder()\n        # 撤单后买入/卖出/平仓\n        res = cancleorder.c_cancel_sell()\n>       assert res == True\nE       assert False == True\nE         +False\nE         -True\n\ntestCancelOrder\\test_Qcancelorder.py:85: AssertionError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "bdb60f43a7284397",
      "name" : "log",
      "source" : "bdb60f43a7284397.txt",
      "type" : "text/plain",
      "size" : 2155
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 1
  },
  "afterStages" : [ {
    "name" : "driver_fixture::0",
    "time" : {
      "start" : 1652796124797,
      "stop" : 1652796124797,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "back_fixture::0",
    "time" : {
      "start" : 1652794659600,
      "stop" : 1652794659733,
      "duration" : 133
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('back_fixture')"
  }, {
    "name" : "parentSuite",
    "value" : "testCancelOrder"
  }, {
    "name" : "suite",
    "value" : "test_Qcancelorder"
  }, {
    "name" : "subSuite",
    "value" : "TestCancelOrder"
  }, {
    "name" : "host",
    "value" : "Win102021AVUCSJ"
  }, {
    "name" : "thread",
    "value" : "10404-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testCancelOrder.test_Qcancelorder"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "6da8595287e6fe56",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0400E0D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1652793912503,
        "stop" : 1652793912503,
        "duration" : 0
      }
    }, {
      "uid" : "ce8ae6b6ce56daca",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652712842698,
        "stop" : 1652712854141,
        "duration" : 11443
      }
    }, {
      "uid" : "a4adc22863ad8f68",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652712637606,
        "stop" : 1652712649161,
        "duration" : 11555
      }
    }, {
      "uid" : "3d08c6bb4f32a093",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652710821473,
        "stop" : 1652710821473,
        "duration" : 0
      }
    }, {
      "uid" : "5f201589ed52116b",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652710341429,
        "stop" : 1652710341429,
        "duration" : 0
      }
    }, {
      "uid" : "58ec1d4f372b005b",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20093ms.",
      "time" : {
        "start" : 1652710085127,
        "stop" : 1652710085127,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "@pytest.mark.usefixtures('back_fixture')" ]
  },
  "source" : "c8a5e3e3bddfaf28.json",
  "parameterValues" : [ ]
}