{
  "uid" : "ee77ff0fb9424c3d",
  "name" : "test_cancel",
  "fullName" : "testCancelOrder.test_Qcancelorder.TestCancelOrder#test_cancel",
  "historyId" : "8b0b1b35a848e9872c7ddefad090e096",
  "time" : {
    "start" : 1652794539800,
    "stop" : 1652794575946,
    "duration" : 36146
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: assert False == True\n  +False\n  -True",
  "statusTrace" : "self = <testcases.testCancelOrder.test_Qcancelorder.TestCancelOrder object at 0x001E91B0>\nsetup_fixture = (<businessPage.cancel_order_page.CancelOrder object at 0x001E9C30>, <businessPage.trade_first_page.TradeFirst object a...<businessPage.choice_oder_page.ChoiceOrder object at 0x001E9B90>, <businessPage.order_page.Order object at 0x001E9C50>)\n\n    @pytest.mark.usefixtures('back_fixture')\n    def test_cancel(self,setup_fixture):\n        cancleorder,tradehome,choiceorder,order= setup_fixture\n        # 构造1个撤单数据\n        tradehome.to_trade_page()\n        tradehome.to_order()\n        choiceorder.c_orderpage()\n        order.c_price_ztj()\n        order.c_hand(1)\n        order.c_ordersell()\n        order.order_page_back()\n        # 进入撤单页\n        tradehome.to_cancelOrder()\n        res = cancleorder.c_cancel()\n>       assert res == True\nE       assert False == True\nE         +False\nE         -True\n\ntestCancelOrder\\test_Qcancelorder.py:52: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "driver_fixture",
    "time" : {
      "start" : 1652794360868,
      "stop" : 1652794396581,
      "duration" : 35713
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "login_fixture",
    "time" : {
      "start" : 1652794396581,
      "stop" : 1652794501486,
      "duration" : 104905
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "setup_fixture",
    "time" : {
      "start" : 1652794539800,
      "stop" : 1652794539800,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "back_fixture",
    "time" : {
      "start" : 1652794539800,
      "stop" : 1652794539800,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: assert False == True\n  +False\n  -True",
    "statusTrace" : "self = <testcases.testCancelOrder.test_Qcancelorder.TestCancelOrder object at 0x001E91B0>\nsetup_fixture = (<businessPage.cancel_order_page.CancelOrder object at 0x001E9C30>, <businessPage.trade_first_page.TradeFirst object a...<businessPage.choice_oder_page.ChoiceOrder object at 0x001E9B90>, <businessPage.order_page.Order object at 0x001E9C50>)\n\n    @pytest.mark.usefixtures('back_fixture')\n    def test_cancel(self,setup_fixture):\n        cancleorder,tradehome,choiceorder,order= setup_fixture\n        # 构造1个撤单数据\n        tradehome.to_trade_page()\n        tradehome.to_order()\n        choiceorder.c_orderpage()\n        order.c_price_ztj()\n        order.c_hand(1)\n        order.c_ordersell()\n        order.order_page_back()\n        # 进入撤单页\n        tradehome.to_cancelOrder()\n        res = cancleorder.c_cancel()\n>       assert res == True\nE       assert False == True\nE         +False\nE         -True\n\ntestCancelOrder\\test_Qcancelorder.py:52: AssertionError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "e349804c47c97120",
      "name" : "log",
      "source" : "e349804c47c97120.txt",
      "type" : "text/plain",
      "size" : 2155
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 1
  },
  "afterStages" : [ {
    "name" : "driver_fixture::0",
    "time" : {
      "start" : 1652796124797,
      "stop" : 1652796124797,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "back_fixture::0",
    "time" : {
      "start" : 1652794575953,
      "stop" : 1652794576071,
      "duration" : 118
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('back_fixture')"
  }, {
    "name" : "parentSuite",
    "value" : "testCancelOrder"
  }, {
    "name" : "suite",
    "value" : "test_Qcancelorder"
  }, {
    "name" : "subSuite",
    "value" : "TestCancelOrder"
  }, {
    "name" : "host",
    "value" : "Win102021AVUCSJ"
  }, {
    "name" : "thread",
    "value" : "10404-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testCancelOrder.test_Qcancelorder"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "966edb8b3fe9f490",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0400E0D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1652793912144,
        "stop" : 1652793912144,
        "duration" : 0
      }
    }, {
      "uid" : "7e8f5cf309319520",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652712797116,
        "stop" : 1652712808511,
        "duration" : 11395
      }
    }, {
      "uid" : "24793eee97e921de",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652712592354,
        "stop" : 1652712603865,
        "duration" : 11511
      }
    }, {
      "uid" : "8a8b7eafd6557667",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652710821416,
        "stop" : 1652710821416,
        "duration" : 0
      }
    }, {
      "uid" : "67145a1afa3626b4",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652710341371,
        "stop" : 1652710341371,
        "duration" : 0
      }
    }, {
      "uid" : "30af313f153e623b",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20093ms.",
      "time" : {
        "start" : 1652710085030,
        "stop" : 1652710085030,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "@pytest.mark.usefixtures('back_fixture')" ]
  },
  "source" : "ee77ff0fb9424c3d.json",
  "parameterValues" : [ ]
}