{
  "uid" : "f4e26a2fedb7efa6",
  "name" : "test_relieveComb",
  "fullName" : "testCombinationReport.test_Xcombination_report.TestEntrustSetup#test_relieveComb",
  "historyId" : "913f8e09e1cd3739eea2697ab8b5a60c",
  "time" : {
    "start" : 1652794927053,
    "stop" : 1652794940004,
    "duration" : 12951
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: assert False == True\n  +False\n  -True",
  "statusTrace" : "self = <testcases.testCombinationReport.test_Xcombination_report.TestEntrustSetup object at 0x005F6790>\nsetup_fixture = (<businessPage.trade_first_page.TradeFirst object at 0x00603A70>, <businessPage.choice_oder_page.ChoiceOrder object at....order_page.Order object at 0x006032F0>, <businessPage.combination_report_page.CombinationReport object at 0x00603810>)\n\n    @pytest.mark.usefixtures('back_fixture')\n    def test_relieveComb(self,setup_fixture):\n        tradehome, choiceorder, order, combinationreport = setup_fixture\n        tradehome.to_comb_report()\n        res = combinationreport.relieveComb()\n>       assert res == True\nE       assert False == True\nE         +False\nE         -True\n\ntestCombinationReport\\test_Xcombination_report.py:53: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "back_fixture",
    "time" : {
      "start" : 1652794925691,
      "stop" : 1652794925691,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "driver_fixture",
    "time" : {
      "start" : 1652794360868,
      "stop" : 1652794396581,
      "duration" : 35713
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "login_fixture",
    "time" : {
      "start" : 1652794396581,
      "stop" : 1652794501486,
      "duration" : 104905
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "setup_fixture",
    "time" : {
      "start" : 1652794925692,
      "stop" : 1652794927052,
      "duration" : 1360
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: assert False == True\n  +False\n  -True",
    "statusTrace" : "self = <testcases.testCombinationReport.test_Xcombination_report.TestEntrustSetup object at 0x005F6790>\nsetup_fixture = (<businessPage.trade_first_page.TradeFirst object at 0x00603A70>, <businessPage.choice_oder_page.ChoiceOrder object at....order_page.Order object at 0x006032F0>, <businessPage.combination_report_page.CombinationReport object at 0x00603810>)\n\n    @pytest.mark.usefixtures('back_fixture')\n    def test_relieveComb(self,setup_fixture):\n        tradehome, choiceorder, order, combinationreport = setup_fixture\n        tradehome.to_comb_report()\n        res = combinationreport.relieveComb()\n>       assert res == True\nE       assert False == True\nE         +False\nE         -True\n\ntestCombinationReport\\test_Xcombination_report.py:53: AssertionError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "88107fdd558862cb",
      "name" : "log",
      "source" : "88107fdd558862cb.txt",
      "type" : "text/plain",
      "size" : 928
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 1
  },
  "afterStages" : [ {
    "name" : "back_fixture::0",
    "time" : {
      "start" : 1652794940008,
      "stop" : 1652794940081,
      "duration" : 73
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "driver_fixture::0",
    "time" : {
      "start" : 1652796124797,
      "stop" : 1652796124797,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('back_fixture')"
  }, {
    "name" : "parentSuite",
    "value" : "testCombinationReport"
  }, {
    "name" : "suite",
    "value" : "test_Xcombination_report"
  }, {
    "name" : "subSuite",
    "value" : "TestEntrustSetup"
  }, {
    "name" : "host",
    "value" : "Win102021AVUCSJ"
  }, {
    "name" : "thread",
    "value" : "10404-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testCombinationReport.test_Xcombination_report"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "1d8c69378213e890",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0400E0D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1652793915164,
        "stop" : 1652793915164,
        "duration" : 0
      }
    }, {
      "uid" : "7730be08fb26633e",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details",
      "time" : {
        "start" : 1652713044805,
        "stop" : 1652713044805,
        "duration" : 0
      }
    }, {
      "uid" : "4db6ebd81039fa8",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details",
      "time" : {
        "start" : 1652712701242,
        "stop" : 1652712701242,
        "duration" : 0
      }
    }, {
      "uid" : "d8a07a1a63503265",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652710821922,
        "stop" : 1652710821922,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "@pytest.mark.usefixtures('back_fixture')" ]
  },
  "source" : "f4e26a2fedb7efa6.json",
  "parameterValues" : [ ]
}