{
  "uid" : "feb42cf529efff1c",
  "name" : "test_new_price",
  "fullName" : "testContractScreen.test_Qcontract_screen.TestContractScreen#test_new_price",
  "historyId" : "e1167ff116ea9aead7e4de9e75bcdfaf",
  "time" : {
    "start" : 1652794943008,
    "stop" : 1652794947614,
    "duration" : 4606
  },
  "status" : "broken",
  "statusMessage" : "AttributeError: module 'pytest' has no attribute 'assume'",
  "statusTrace" : "self = <testcases.testContractScreen.test_Qcontract_screen.TestContractScreen object at 0x00603C90>\nsetup_fixture = (<businessPage.contract_screen_page.Screen object at 0x006030F0>, <businessPage.first_page.First object at 0x00603DB0>, <businessPage.optional_page.Optional object at 0x006032D0>)\n\n    @pytest.mark.usefixtures('back_fixture')\n    def test_new_price(self, setup_fixture):\n        screen,first,optional = setup_fixture\n        # 降序\n        screen.c_new_price()\n        res = screen.desc(1)\n>       pytest.assume(res == True)\nE       AttributeError: module 'pytest' has no attribute 'assume'\n\ntestContractScreen\\test_Qcontract_screen.py:30: AttributeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "driver_fixture",
    "time" : {
      "start" : 1652794360868,
      "stop" : 1652794396581,
      "duration" : 35713
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "login_fixture",
    "time" : {
      "start" : 1652794396581,
      "stop" : 1652794501486,
      "duration" : 104905
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "setup_fixture",
    "time" : {
      "start" : 1652794940085,
      "stop" : 1652794943008,
      "duration" : 2923
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "back_fixture",
    "time" : {
      "start" : 1652794940085,
      "stop" : 1652794940085,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "AttributeError: module 'pytest' has no attribute 'assume'",
    "statusTrace" : "self = <testcases.testContractScreen.test_Qcontract_screen.TestContractScreen object at 0x00603C90>\nsetup_fixture = (<businessPage.contract_screen_page.Screen object at 0x006030F0>, <businessPage.first_page.First object at 0x00603DB0>, <businessPage.optional_page.Optional object at 0x006032D0>)\n\n    @pytest.mark.usefixtures('back_fixture')\n    def test_new_price(self, setup_fixture):\n        screen,first,optional = setup_fixture\n        # 降序\n        screen.c_new_price()\n        res = screen.desc(1)\n>       pytest.assume(res == True)\nE       AttributeError: module 'pytest' has no attribute 'assume'\n\ntestContractScreen\\test_Qcontract_screen.py:30: AttributeError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "ff4628fcc3126a72",
      "name" : "log",
      "source" : "ff4628fcc3126a72.txt",
      "type" : "text/plain",
      "size" : 622
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 1
  },
  "afterStages" : [ {
    "name" : "driver_fixture::0",
    "time" : {
      "start" : 1652796124797,
      "stop" : 1652796124797,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "back_fixture::0",
    "time" : {
      "start" : 1652794947620,
      "stop" : 1652794947752,
      "duration" : 132
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('back_fixture')"
  }, {
    "name" : "parentSuite",
    "value" : "testContractScreen"
  }, {
    "name" : "suite",
    "value" : "test_Qcontract_screen"
  }, {
    "name" : "subSuite",
    "value" : "TestContractScreen"
  }, {
    "name" : "host",
    "value" : "Win102021AVUCSJ"
  }, {
    "name" : "thread",
    "value" : "10404-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testContractScreen.test_Qcontract_screen"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "be9489c156227da9",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0400E0D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1652793915339,
        "stop" : 1652793915339,
        "duration" : 0
      }
    }, {
      "uid" : "c55287e02bbe9efc",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details",
      "time" : {
        "start" : 1652713045060,
        "stop" : 1652713045060,
        "duration" : 0
      }
    }, {
      "uid" : "408347ddf82edf13",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details",
      "time" : {
        "start" : 1652712701522,
        "stop" : 1652712701522,
        "duration" : 0
      }
    }, {
      "uid" : "99eeb05d612a390d",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652710821952,
        "stop" : 1652710821952,
        "duration" : 0
      }
    }, {
      "uid" : "8d2a263379169a66",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.TimeoutException: Message:",
      "time" : {
        "start" : 1652710341845,
        "stop" : 1652710341845,
        "duration" : 0
      }
    }, {
      "uid" : "2f6db073b6ce99c1",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20093ms.",
      "time" : {
        "start" : 1652710085793,
        "stop" : 1652710085793,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "@pytest.mark.usefixtures('back_fixture')" ]
  },
  "source" : "feb42cf529efff1c.json",
  "parameterValues" : [ ]
}